ARG BASE_IMAGE=python:3.10-slim

FROM $BASE_IMAGE

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y git
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade wheel

# pytiff
RUN apt-get install -y gcc build-essential libtiff-dev
RUN pip3 install git+https://github.com/FZJ-INM1-BDA/pytiff
