"""
Metadata on images.
"""

from collections.abc import Iterable
from dataclasses import dataclass, field, fields
from itertools import product, repeat
from typing import Mapping, Any

import numpy as np

import tiamat.metadata.dimensions as dimensions

# Image types
IMAGE_TYPE_SEGMENTATION = "segmentation"  # an image with discrete values, e.g., a mask or a segmentation.
IMAGE_TYPE_IMAGE = "image"  # an image with continuous values (e.g., a microscopy image).
IMAGE_TYPE_VECTOR = "vector"  # an image with continuous vector values (e.g., a deformation field).


def get_dtype_limits(dtype):
    """Returns the min and max values for a given dtype.

    Supports numpy dtypes (integer or float)

    Args:
        dtype: numpy dtype

    Returns:
        tuple: min and max value of the dtype.
    """

    dtype = np.dtype(dtype)

    if issubclass(dtype.type, np.integer):
        info = np.iinfo(dtype)
    elif issubclass(dtype.type, np.floating):
        info = np.finfo(dtype)
    else:
        raise RuntimeError(f"{dtype} is not a valid dtype")
    return info.min, info.max


@dataclass
class ImageMetadata:
    """
    Metadata describing an image result and its storage properties.

    Attributes
    ----------
    image_type:
        Logical type of the image defining how its data should be interpreted.
        Typical examples include raw intensity images, segmentation masks,
        or vector fields.

        Must be one of:

        - ``tiamat.metadata.IMAGE_TYPE_SEGMENTATION``
        - ``tiamat.metadata.IMAGE_TYPE_IMAGE``
        - ``tiamat.metadata.IMAGE_TYPE_VECTOR``

    shape:
        Shape of the image array at full resolution, expressed as a tuple
        of integers describing the number of pixels or voxels along each
        dimension.

        The default dimension order is ``(z, y, x)``. This order matches the
        typical indexing order used in NumPy arrays and ensures efficient
        memory access.

    value_range:
        Expected minimum and maximum values of the image data, given as
        ``(min, max)``.

        The range is typically derived from the limits of ``dtype``,
        but can also refer to the expected modality-specific limits.

        This information may be used for normalization, data type conversion,
        or visualization.

    dtype:
        NumPy data type used to store the image values.

    dimensions:
        Ordered names of the dimensions corresponding to ``shape``.
        Valid dimension names are defined in ``tiamat.metadata.dimensions``.

        The default order is ``(y, x, c)``, with the channel dimension
        placed last.

    file_path:
        Path or collection of paths pointing to the file(s) storing the
        image data.

        Multiple paths typically indicate that the image data is read from
        multiple files (for example an image stack). May be ``None`` if
        the image is not associated with files on disk.

    spacing:
        Physical spacing between pixels or voxels at full resolution,
        expressed in micrometers.

        The value may be a single scalar (uniform spacing) or a tuple
        specifying spacing per spatial dimension. Spacing is defined only
        for spatial dimensions and does not apply to channel dimensions.

        The dimension order follows ``(x, y)`` or ``(x, y, z)``.

    additional_metadata:
        Dictionary containing arbitrary additional metadata that is not
        covered by the standard attributes.

        This dictionary may contain reader-specific metadata or metadata
        generated by the transform_metadata functions.

    scales:
        Scaling factors describing the available resolution levels of the
        image (for example in a multi-resolution pyramid).

        The value may be a single scale or an iterable of scales if multiple
        resolutions are available.

        Each scale may be either:

        - a single numeric value for isotropic scaling, or
        - a tuple specifying one scale value per spatial dimension.

        A scale of ``1.0`` refers to the image at full resolution. Smaller
        values indicate downsampled versions relative to the original size
        (e.g. ``0.5`` corresponds to a downsampling factor of two).

        The dimension order follows ``(x, y)`` or ``(x, y, z)``.
    """

    image_type: str
    shape: tuple
    value_range: tuple
    dtype: np.dtype
    dimensions: list[str, ...] | tuple[str, ...] = (dimensions.Y, dimensions.X, dimensions.C)
    file_path: Iterable[str] | str | None = None
    spacing: float | tuple[float, ...] | None = None
    additional_metadata: dict = field(default_factory=dict)
    scales: float | int | Iterable[float | int] | Iterable[tuple[float | int, ...]] | None = None

    @property
    def spatial_dimensions(self):
        """
        Returns indices of spatial dimensions, excluding channels
        """
        return tuple(
            self.dimensions.index(dimension)
            for dimension in dimensions.SPATIAL_DIMENSIONS
            if dimension in self.dimensions
        )

    @property
    def channel_dimensions(self):
        """
        Returns indices of channels, excluding spatial dimensions
        """
        return tuple(index for index, _ in enumerate(self.shape) if index not in self.spatial_dimensions)

    @property
    def spatial_shape(self):
        """
        Spatial shape of the image array, ignoring channel dimensions
        """
        return tuple(self.shape[i] for i in self.spatial_dimensions)

    @spatial_shape.setter
    def spatial_shape(self, shape):
        shape_list = list(self.shape)
        for i, ix in enumerate(self.spatial_dimensions):
            shape_list[ix] = shape[i]
        self.shape = tuple(shape_list)

    @property
    def extents(self):
        """
        Extents of the image. Provided as a list of tuple of coordinates.
        Extrapolated by shape. Can be set, and will then return the set value.
        Delete the property to revert to the default behavior.
        """
        if hasattr(self, "_extents"):
            return self._extents
        extents = list(zip(repeat(0), self.shape))
        return list(product(*extents))

    @extents.deleter
    def extents(self):
        delattr(self, "_extents")

    def __repr__(self):
        return (
            f"ImageMetadata(\n"
            f"  image_type={self.image_type},\n"
            f"  shape={self.shape},\n"
            f"  value_range={self.value_range},\n"
            f"  dtype={self.dtype},\n"
            f"  spacing={self.spacing},\n"
            f"  dimensions=({','.join(self.dimensions)}),\n"
            f"  additional_metadata={self.additional_metadata},\n"
            f"  scales={self.scales}\n"
            f")"
        )

    def __str__(self):
        return self.__repr__()


def _convert_metadata_value(key: str, value: Any) -> Any:
    """Convert metadata values to match ImageMetadata field conventions."""
    if key in {"shape", "value_range", "dimensions", "spacing"}:
        if isinstance(value, list):
            return tuple(value)

    if key == "dtype":
        if isinstance(value, str):
            return np.dtype(value)

    if key == "scales":
        if isinstance(value, list):
            if value and all(isinstance(v, (list, tuple)) for v in value):
                return [tuple(v) for v in value]

    return value


def update_metadata_from_dict(
    image_metadata: ImageMetadata,
    update_dict: Mapping[str, Any],
) -> ImageMetadata:
    """
    Update an ImageMetadata instance from a dict.

    Matching keys update dataclass fields; unknown keys are stored in
    ``additional_metadata``.
    """
    valid_fields = {f.name for f in fields(image_metadata)}

    for key, value in update_dict.items():
        if key in valid_fields:
            setattr(image_metadata, key, _convert_metadata_value(key, value))
        else:
            image_metadata.additional_metadata[key] = value

    return image_metadata